#!/bin/bash
# Build an UNSIGNED .ipa for TumoCompanion.
# Sign it afterwards with your developer cert via Feather Pro / Sideloadly.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
XCODE="/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild"
PATH="/opt/homebrew/bin:$PATH"
XCODE_JOBS="${XCODE_JOBS:-2}"

VERSION=$(awk -F'"' '/MARKETING_VERSION:/{print $2; exit}' project.yml)
STAMP="${BUILD_STAMP:-$(date +%Y%m%d-%H%M)}"
COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo local)"
if ! git diff --quiet -- . ':!Sources/App/BuildInfo.swift'; then
  COMMIT="$COMMIT-dirty"
fi
echo "==> Validating Clear icon alpha assets"
scripts/validate_icon_assets.sh

echo "==> Stamping BuildInfo: v$VERSION · $COMMIT · $STAMP"
cat > Sources/App/BuildInfo.swift <<EOF
import Foundation

/// Generated by scripts/build_ipa.sh on every build. The source commit and
/// timestamp make each IPA uniquely identifiable on the device.
enum BuildInfo {
    static let version = "$VERSION"
    static let commit = "$COMMIT"
    static let build = "$STAMP"
    static var label: String { "v\\(version) · \\(commit)" }
}
EOF

echo "==> Regenerating project (XcodeGen)"
xcodegen generate

echo "==> Resolving Swift packages"
"$XCODE" -resolvePackageDependencies \
  -project UnleashedCompanion.xcodeproj -scheme UnleashedCompanion >/dev/null

echo "==> Building (Release, iphoneos, unsigned)"
"$XCODE" build \
  -project UnleashedCompanion.xcodeproj -scheme UnleashedCompanion \
  -sdk iphoneos -configuration Release -destination 'generic/platform=iOS' \
  -jobs "$XCODE_JOBS" \
  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO | tail -3

APP=$("$XCODE" -project UnleashedCompanion.xcodeproj -scheme UnleashedCompanion \
  -sdk iphoneos -configuration Release -showBuildSettings -json 2>/dev/null \
  | python3 -c '
import json
import os
import sys

settings = next(
    (item["buildSettings"] for item in json.load(sys.stdin)
     if item.get("target") == "UnleashedCompanion"),
    None,
)
if settings is None:
    raise SystemExit("UnleashedCompanion build settings not found")
print(os.path.join(settings["TARGET_BUILD_DIR"], settings["FULL_PRODUCT_NAME"]))
')

if [ ! -d "$APP" ] || [ "${APP##*.}" != "app" ]; then
  echo "error: expected UnleashedCompanion.app, got: $APP" >&2
  exit 1
fi
if [ "$(plutil -extract CFBundlePackageType raw "$APP/Info.plist")" != "APPL" ]; then
  echo "error: build product is not an iOS application: $APP" >&2
  exit 1
fi

# Sign nested code first (shared framework, then the Live Activity extension),
# followed by the outer app. Home Screen widgets and their App Group were removed;
# the extension remains because ActivityKit renders Live Activities through it.
echo "==> Ad-hoc signing nested code and app"
APPEX="$APP/PlugIns/UnleashedWidgets.appex"
if [ -d "$APP/Frameworks" ]; then
  for fw in "$APP/Frameworks/"*; do
    [ -e "$fw" ] && codesign --force --sign - --timestamp=none "$fw" >/dev/null 2>&1 || true
  done
fi
if [ -d "$APPEX" ]; then
  codesign --force --sign - --timestamp=none "$APPEX"
fi
codesign --force --sign - --timestamp=none \
  --entitlements "$ROOT/Resources/UnleashedCompanion.entitlements" "$APP"

echo "==> Packaging IPA from $APP"
rm -rf build/ipa
mkdir -p build/ipa/Payload
cp -R "$APP" build/ipa/Payload/

# Always create a new archive. Updating an existing ZIP keeps entries that no
# longer exist in the app bundle, which invalidates the outer code signature.
PACKAGE_DIR=$(mktemp -d "$ROOT/build/.ipa-package.XXXXXX")
CHECK_DIR=$(mktemp -d "$ROOT/build/.ipa-check.XXXXXX")
PACKAGE_IPA="$PACKAGE_DIR/TumoCompanion-unsigned.ipa"
cleanup_ipa_temp() {
  rm -rf "$PACKAGE_DIR" "$CHECK_DIR"
}
trap cleanup_ipa_temp EXIT
( cd build/ipa && zip -qr "$PACKAGE_IPA" Payload )
ditto -x -k "$PACKAGE_IPA" "$CHECK_DIR"
codesign --verify --deep --strict "$CHECK_DIR/Payload/UnleashedCompanion.app"
mv -f "$PACKAGE_IPA" "$ROOT/build/TumoCompanion-unsigned.ipa"
cleanup_ipa_temp
trap - EXIT

echo "==> Done: build/TumoCompanion-unsigned.ipa"
ls -lh build/TumoCompanion-unsigned.ipa
